CITOYEN = "citoyen"
MAIRE = "maire"
DEPUTE = "député"
DEPUTE_REGIONAL = "député régional"
MINISTRE = "ministre"
PRESIDENT = "président"
PRESIDENT_DES_NATIONS = "président des nations"
EVENT = "event"
GRADE = "grade"
FIN_GAGNE = 0
FIN_TEMPS = 1
FIN_PRISON = 2
FIN_DICT_VIDE = 3
BLANC = (255, 255, 255)
NOIR  = (0, 0, 0)