CITOYEN = "citoyen"
MAIRE = "maire"
DEPUTE = "député"
DEPUTE_REGIONAL = "député régional"
MINISTRE = "ministre"
PRESIDENT = "président"
PRESIDENT_DES_NATIONS = "président des nations"
FIN_GAGNE = 0
FIN_TEMPS = 1
FIN_PRISON = 2
